# CMake generated Testfile for 
# Source directory: C:/Diablo/DevilutionX Repo/DevilutionX
# Build directory: C:/Diablo/DevilutionX Repo/DevilutionX/build_final_working
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
include("C:/Diablo/DevilutionX Repo/DevilutionX/build_final_working/animationinfo_test[1]_include.cmake")
include("C:/Diablo/DevilutionX Repo/DevilutionX/build_final_working/appfat_test[1]_include.cmake")
include("C:/Diablo/DevilutionX Repo/DevilutionX/build_final_working/automap_test[1]_include.cmake")
include("C:/Diablo/DevilutionX Repo/DevilutionX/build_final_working/cursor_test[1]_include.cmake")
include("C:/Diablo/DevilutionX Repo/DevilutionX/build_final_working/dead_test[1]_include.cmake")
include("C:/Diablo/DevilutionX Repo/DevilutionX/build_final_working/diablo_test[1]_include.cmake")
include("C:/Diablo/DevilutionX Repo/DevilutionX/build_final_working/drlg_common_test[1]_include.cmake")
include("C:/Diablo/DevilutionX Repo/DevilutionX/build_final_working/drlg_l1_test[1]_include.cmake")
include("C:/Diablo/DevilutionX Repo/DevilutionX/build_final_working/drlg_l2_test[1]_include.cmake")
include("C:/Diablo/DevilutionX Repo/DevilutionX/build_final_working/drlg_l3_test[1]_include.cmake")
include("C:/Diablo/DevilutionX Repo/DevilutionX/build_final_working/drlg_l4_test[1]_include.cmake")
include("C:/Diablo/DevilutionX Repo/DevilutionX/build_final_working/effects_test[1]_include.cmake")
include("C:/Diablo/DevilutionX Repo/DevilutionX/build_final_working/inv_test[1]_include.cmake")
include("C:/Diablo/DevilutionX Repo/DevilutionX/build_final_working/items_test[1]_include.cmake")
include("C:/Diablo/DevilutionX Repo/DevilutionX/build_final_working/math_test[1]_include.cmake")
include("C:/Diablo/DevilutionX Repo/DevilutionX/build_final_working/missiles_test[1]_include.cmake")
include("C:/Diablo/DevilutionX Repo/DevilutionX/build_final_working/multi_logging_test[1]_include.cmake")
include("C:/Diablo/DevilutionX Repo/DevilutionX/build_final_working/pack_test[1]_include.cmake")
include("C:/Diablo/DevilutionX Repo/DevilutionX/build_final_working/player_test[1]_include.cmake")
include("C:/Diablo/DevilutionX Repo/DevilutionX/build_final_working/quests_test[1]_include.cmake")
include("C:/Diablo/DevilutionX Repo/DevilutionX/build_final_working/scrollrt_test[1]_include.cmake")
include("C:/Diablo/DevilutionX Repo/DevilutionX/build_final_working/stores_test[1]_include.cmake")
include("C:/Diablo/DevilutionX Repo/DevilutionX/build_final_working/tile_properties_test[1]_include.cmake")
include("C:/Diablo/DevilutionX Repo/DevilutionX/build_final_working/timedemo_test[1]_include.cmake")
include("C:/Diablo/DevilutionX Repo/DevilutionX/build_final_working/townerdat_test[1]_include.cmake")
include("C:/Diablo/DevilutionX Repo/DevilutionX/build_final_working/writehero_test[1]_include.cmake")
include("C:/Diablo/DevilutionX Repo/DevilutionX/build_final_working/vendor_test[1]_include.cmake")
include("C:/Diablo/DevilutionX Repo/DevilutionX/build_final_working/codec_test[1]_include.cmake")
include("C:/Diablo/DevilutionX Repo/DevilutionX/build_final_working/crawl_test[1]_include.cmake")
include("C:/Diablo/DevilutionX Repo/DevilutionX/build_final_working/data_file_test[1]_include.cmake")
include("C:/Diablo/DevilutionX Repo/DevilutionX/build_final_working/file_util_test[1]_include.cmake")
include("C:/Diablo/DevilutionX Repo/DevilutionX/build_final_working/format_int_test[1]_include.cmake")
include("C:/Diablo/DevilutionX Repo/DevilutionX/build_final_working/ini_test[1]_include.cmake")
include("C:/Diablo/DevilutionX Repo/DevilutionX/build_final_working/palette_blending_test[1]_include.cmake")
include("C:/Diablo/DevilutionX Repo/DevilutionX/build_final_working/parse_int_test[1]_include.cmake")
include("C:/Diablo/DevilutionX Repo/DevilutionX/build_final_working/path_test[1]_include.cmake")
include("C:/Diablo/DevilutionX Repo/DevilutionX/build_final_working/vision_test[1]_include.cmake")
include("C:/Diablo/DevilutionX Repo/DevilutionX/build_final_working/random_test[1]_include.cmake")
include("C:/Diablo/DevilutionX Repo/DevilutionX/build_final_working/rectangle_test[1]_include.cmake")
include("C:/Diablo/DevilutionX Repo/DevilutionX/build_final_working/static_vector_test[1]_include.cmake")
include("C:/Diablo/DevilutionX Repo/DevilutionX/build_final_working/str_cat_test[1]_include.cmake")
include("C:/Diablo/DevilutionX Repo/DevilutionX/build_final_working/utf8_test[1]_include.cmake")
include("C:/Diablo/DevilutionX Repo/DevilutionX/build_final_working/text_render_integration_test[1]_include.cmake")
subdirs("3rdParty/Lua")
subdirs("3rdParty/sol2")
subdirs("3rdParty/SDL_audiolib")
subdirs("3rdParty/libsmackerdec")
subdirs("3rdParty/find_steam_game")
subdirs("3rdParty/libmpq")
subdirs("3rdParty/tl")
subdirs("3rdParty/SheenBidi")
subdirs("3rdParty/unordered_dense")
subdirs("3rdParty/magic_enum")
subdirs("3rdParty/PKWare")
subdirs("Source")
