if(EXISTS "C:/Diablo/DevilutionX Repo/DevilutionX/build_final_working/math_test[1]_tests.cmake")
  include("C:/Diablo/DevilutionX Repo/DevilutionX/build_final_working/math_test[1]_tests.cmake")
else()
  add_test(math_test_NOT_BUILT math_test_NOT_BUILT)
endif()
