if(EXISTS "C:/Diablo/DevilutionX Repo/DevilutionX/build_final_working/static_vector_test[1]_tests.cmake")
  include("C:/Diablo/DevilutionX Repo/DevilutionX/build_final_working/static_vector_test[1]_tests.cmake")
else()
  add_test(static_vector_test_NOT_BUILT static_vector_test_NOT_BUILT)
endif()
