if(EXISTS "C:/Diablo/DevilutionX Repo/DevilutionX/build_final_working/inv_test[1]_tests.cmake")
  include("C:/Diablo/DevilutionX Repo/DevilutionX/build_final_working/inv_test[1]_tests.cmake")
else()
  add_test(inv_test_NOT_BUILT inv_test_NOT_BUILT)
endif()
