if(EXISTS "C:/Diablo/DevilutionX Repo/DevilutionX/build_final_working/missiles_test[1]_tests.cmake")
  include("C:/Diablo/DevilutionX Repo/DevilutionX/build_final_working/missiles_test[1]_tests.cmake")
else()
  add_test(missiles_test_NOT_BUILT missiles_test_NOT_BUILT)
endif()
