if(EXISTS "C:/Diablo/DevilutionX Repo/DevilutionX/build_final_working/stores_test[1]_tests.cmake")
  include("C:/Diablo/DevilutionX Repo/DevilutionX/build_final_working/stores_test[1]_tests.cmake")
else()
  add_test(stores_test_NOT_BUILT stores_test_NOT_BUILT)
endif()
