if(EXISTS "C:/Diablo/DevilutionX Repo/DevilutionX/build_final_working/crawl_test[1]_tests.cmake")
  include("C:/Diablo/DevilutionX Repo/DevilutionX/build_final_working/crawl_test[1]_tests.cmake")
else()
  add_test(crawl_test_NOT_BUILT crawl_test_NOT_BUILT)
endif()
