if(EXISTS "C:/Diablo/DevilutionX Repo/DevilutionX/build_final_working/drlg_common_test[1]_tests.cmake")
  include("C:/Diablo/DevilutionX Repo/DevilutionX/build_final_working/drlg_common_test[1]_tests.cmake")
else()
  add_test(drlg_common_test_NOT_BUILT drlg_common_test_NOT_BUILT)
endif()
