if(EXISTS "C:/Diablo/DevilutionX Repo/DevilutionX/build_final_working/ini_test[1]_tests.cmake")
  include("C:/Diablo/DevilutionX Repo/DevilutionX/build_final_working/ini_test[1]_tests.cmake")
else()
  add_test(ini_test_NOT_BUILT ini_test_NOT_BUILT)
endif()
