if(EXISTS "C:/Diablo/DevilutionX Repo/DevilutionX/build_final_working/str_cat_test[1]_tests.cmake")
  include("C:/Diablo/DevilutionX Repo/DevilutionX/build_final_working/str_cat_test[1]_tests.cmake")
else()
  add_test(str_cat_test_NOT_BUILT str_cat_test_NOT_BUILT)
endif()
