if(EXISTS "C:/Diablo/DevilutionX Repo/DevilutionX/build2/animationinfo_test[1]_tests.cmake")
  include("C:/Diablo/DevilutionX Repo/DevilutionX/build2/animationinfo_test[1]_tests.cmake")
else()
  add_test(animationinfo_test_NOT_BUILT animationinfo_test_NOT_BUILT)
endif()
