# CMake generated Testfile for 
# Source directory: C:/Diablo/DevilutionX Repo/DevilutionX
# Build directory: C:/Diablo/DevilutionX Repo/DevilutionX/build2
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
include("C:/Diablo/DevilutionX Repo/DevilutionX/build2/animationinfo_test[1]_include.cmake")
include("C:/Diablo/DevilutionX Repo/DevilutionX/build2/appfat_test[1]_include.cmake")
include("C:/Diablo/DevilutionX Repo/DevilutionX/build2/automap_test[1]_include.cmake")
include("C:/Diablo/DevilutionX Repo/DevilutionX/build2/cursor_test[1]_include.cmake")
include("C:/Diablo/DevilutionX Repo/DevilutionX/build2/dead_test[1]_include.cmake")
include("C:/Diablo/DevilutionX Repo/DevilutionX/build2/diablo_test[1]_include.cmake")
include("C:/Diablo/DevilutionX Repo/DevilutionX/build2/drlg_common_test[1]_include.cmake")
include("C:/Diablo/DevilutionX Repo/DevilutionX/build2/drlg_l1_test[1]_include.cmake")
include("C:/Diablo/DevilutionX Repo/DevilutionX/build2/drlg_l2_test[1]_include.cmake")
include("C:/Diablo/DevilutionX Repo/DevilutionX/build2/drlg_l3_test[1]_include.cmake")
include("C:/Diablo/DevilutionX Repo/DevilutionX/build2/drlg_l4_test[1]_include.cmake")
include("C:/Diablo/DevilutionX Repo/DevilutionX/build2/effects_test[1]_include.cmake")
include("C:/Diablo/DevilutionX Repo/DevilutionX/build2/inv_test[1]_include.cmake")
include("C:/Diablo/DevilutionX Repo/DevilutionX/build2/items_test[1]_include.cmake")
include("C:/Diablo/DevilutionX Repo/DevilutionX/build2/math_test[1]_include.cmake")
include("C:/Diablo/DevilutionX Repo/DevilutionX/build2/missiles_test[1]_include.cmake")
include("C:/Diablo/DevilutionX Repo/DevilutionX/build2/multi_logging_test[1]_include.cmake")
include("C:/Diablo/DevilutionX Repo/DevilutionX/build2/pack_test[1]_include.cmake")
include("C:/Diablo/DevilutionX Repo/DevilutionX/build2/player_test[1]_include.cmake")
include("C:/Diablo/DevilutionX Repo/DevilutionX/build2/quests_test[1]_include.cmake")
include("C:/Diablo/DevilutionX Repo/DevilutionX/build2/scrollrt_test[1]_include.cmake")
include("C:/Diablo/DevilutionX Repo/DevilutionX/build2/stores_test[1]_include.cmake")
include("C:/Diablo/DevilutionX Repo/DevilutionX/build2/tile_properties_test[1]_include.cmake")
include("C:/Diablo/DevilutionX Repo/DevilutionX/build2/timedemo_test[1]_include.cmake")
include("C:/Diablo/DevilutionX Repo/DevilutionX/build2/townerdat_test[1]_include.cmake")
include("C:/Diablo/DevilutionX Repo/DevilutionX/build2/writehero_test[1]_include.cmake")
include("C:/Diablo/DevilutionX Repo/DevilutionX/build2/vendor_test[1]_include.cmake")
include("C:/Diablo/DevilutionX Repo/DevilutionX/build2/codec_test[1]_include.cmake")
include("C:/Diablo/DevilutionX Repo/DevilutionX/build2/crawl_test[1]_include.cmake")
include("C:/Diablo/DevilutionX Repo/DevilutionX/build2/data_file_test[1]_include.cmake")
include("C:/Diablo/DevilutionX Repo/DevilutionX/build2/file_util_test[1]_include.cmake")
include("C:/Diablo/DevilutionX Repo/DevilutionX/build2/format_int_test[1]_include.cmake")
include("C:/Diablo/DevilutionX Repo/DevilutionX/build2/ini_test[1]_include.cmake")
include("C:/Diablo/DevilutionX Repo/DevilutionX/build2/palette_blending_test[1]_include.cmake")
include("C:/Diablo/DevilutionX Repo/DevilutionX/build2/parse_int_test[1]_include.cmake")
include("C:/Diablo/DevilutionX Repo/DevilutionX/build2/path_test[1]_include.cmake")
include("C:/Diablo/DevilutionX Repo/DevilutionX/build2/vision_test[1]_include.cmake")
include("C:/Diablo/DevilutionX Repo/DevilutionX/build2/random_test[1]_include.cmake")
include("C:/Diablo/DevilutionX Repo/DevilutionX/build2/rectangle_test[1]_include.cmake")
include("C:/Diablo/DevilutionX Repo/DevilutionX/build2/static_vector_test[1]_include.cmake")
include("C:/Diablo/DevilutionX Repo/DevilutionX/build2/str_cat_test[1]_include.cmake")
include("C:/Diablo/DevilutionX Repo/DevilutionX/build2/utf8_test[1]_include.cmake")
include("C:/Diablo/DevilutionX Repo/DevilutionX/build2/text_render_integration_test[1]_include.cmake")
subdirs("3rdParty/zlib")
subdirs("3rdParty/bzip2")
subdirs("3rdParty/Lua")
subdirs("3rdParty/sol2")
subdirs("3rdParty/SDL_audiolib")
subdirs("3rdParty/libsmackerdec")
subdirs("3rdParty/find_steam_game")
subdirs("3rdParty/libmpq")
subdirs("3rdParty/tl")
subdirs("3rdParty/SheenBidi")
subdirs("3rdParty/unordered_dense")
subdirs("3rdParty/magic_enum")
subdirs("3rdParty/PKWare")
subdirs("Source")
