if(EXISTS "C:/Diablo/DevilutionX Repo/DevilutionX/build2/cursor_test[1]_tests.cmake")
  include("C:/Diablo/DevilutionX Repo/DevilutionX/build2/cursor_test[1]_tests.cmake")
else()
  add_test(cursor_test_NOT_BUILT cursor_test_NOT_BUILT)
endif()
