if(EXISTS "C:/Diablo/DevilutionX Repo/DevilutionX/build2/dead_test[1]_tests.cmake")
  include("C:/Diablo/DevilutionX Repo/DevilutionX/build2/dead_test[1]_tests.cmake")
else()
  add_test(dead_test_NOT_BUILT dead_test_NOT_BUILT)
endif()
