if(EXISTS "C:/Diablo/DevilutionX Repo/DevilutionX/build2/effects_test[1]_tests.cmake")
  include("C:/Diablo/DevilutionX Repo/DevilutionX/build2/effects_test[1]_tests.cmake")
else()
  add_test(effects_test_NOT_BUILT effects_test_NOT_BUILT)
endif()
