if(EXISTS "C:/Diablo/DevilutionX Repo/DevilutionX/build2/file_util_test[1]_tests.cmake")
  include("C:/Diablo/DevilutionX Repo/DevilutionX/build2/file_util_test[1]_tests.cmake")
else()
  add_test(file_util_test_NOT_BUILT file_util_test_NOT_BUILT)
endif()
