if(EXISTS "C:/Diablo/DevilutionX Repo/DevilutionX/build2/utf8_test[1]_tests.cmake")
  include("C:/Diablo/DevilutionX Repo/DevilutionX/build2/utf8_test[1]_tests.cmake")
else()
  add_test(utf8_test_NOT_BUILT utf8_test_NOT_BUILT)
endif()
