/**
 * SuborKeyMap.ts
 * 
 * Diccionario y tabla de traducción entre KeyboardEvent.code (DOM moderno)
 * y los identificadores de teclas RETROK_* requeridos por Libretro / FCEUmm / Mesen
 * para la subclase 1539 (RETRO_DEVICE_FC_SUBORKB).
 */

export const RETROK = {
  UNKNOWN: 0,
  FIRST: 0,
  BACKSPACE: 8,
  TAB: 9,
  CLEAR: 12,
  RETURN: 13,
  PAUSE: 19,
  ESCAPE: 27,
  SPACE: 32,
  EXCLAIM: 33,
  QUOTEDBL: 34,
  HASH: 35,
  DOLLAR: 36,
  AMPERSAND: 38,
  QUOTE: 39,
  LEFTPAREN: 40,
  RIGHTPAREN: 41,
  ASTERISK: 42,
  PLUS: 43,
  COMMA: 44,
  MINUS: 45,
  PERIOD: 46,
  SLASH: 47,
  NUM_0: 48,
  NUM_1: 49,
  NUM_2: 50,
  NUM_3: 51,
  NUM_4: 52,
  NUM_5: 53,
  NUM_6: 54,
  NUM_7: 55,
  NUM_8: 56,
  NUM_9: 57,
  COLON: 58,
  SEMICOLON: 59,
  LESS: 60,
  EQUALS: 61,
  GREATER: 62,
  QUESTION: 63,
  AT: 64,
  LEFTBRACKET: 91,
  BACKSLASH: 92,
  RIGHTBRACKET: 93,
  CARET: 94,
  UNDERSCORE: 95,
  BACKQUOTE: 96,
  A: 97,
  B: 98,
  C: 99,
  D: 100,
  E: 101,
  F: 102,
  G: 103,
  H: 104,
  I: 105,
  J: 106,
  K: 107,
  L: 108,
  M: 109,
  N: 110,
  O: 111,
  P: 112,
  Q: 113,
  R: 114,
  S: 115,
  T: 116,
  U: 117,
  V: 118,
  W: 119,
  X: 120,
  Y: 121,
  Z: 122,
  DELETE: 127,

  // Flechas y Navegación
  UP: 273,
  DOWN: 274,
  RIGHT: 275,
  LEFT: 276,
  INSERT: 277,
  HOME: 278,
  END: 279,
  PAGEUP: 280,
  PAGEDOWN: 281,

  // Teclas de Función
  F1: 282,
  F2: 283,
  F3: 284,
  F4: 285,
  F5: 286,
  F6: 287,
  F7: 288,
  F8: 289,
  F9: 290,
  F10: 291,
  F11: 292,
  F12: 293,

  // Modificadores
  RSHIFT: 303,
  LSHIFT: 304,
  RCTRL: 305,
  LCTRL: 306,
  RALT: 307,
  LALT: 308,
  CAPSLOCK: 301
} as const;

export const DOM_TO_RETROK_MAP: Record<string, number> = {
  // Letras A-Z
  KeyA: RETROK.A,
  KeyB: RETROK.B,
  KeyC: RETROK.C,
  KeyD: RETROK.D,
  KeyE: RETROK.E,
  KeyF: RETROK.F,
  KeyG: RETROK.G,
  KeyH: RETROK.H,
  KeyI: RETROK.I,
  KeyJ: RETROK.J,
  KeyK: RETROK.K,
  KeyL: RETROK.L,
  KeyM: RETROK.M,
  KeyN: RETROK.N,
  KeyO: RETROK.O,
  KeyP: RETROK.P,
  KeyQ: RETROK.Q,
  KeyR: RETROK.R,
  KeyS: RETROK.S,
  KeyT: RETROK.T,
  KeyU: RETROK.U,
  KeyV: RETROK.V,
  KeyW: RETROK.W,
  KeyX: RETROK.X,
  KeyY: RETROK.Y,
  KeyZ: RETROK.Z,

  // Fila Numérica 0-9
  Digit0: RETROK.NUM_0,
  Digit1: RETROK.NUM_1,
  Digit2: RETROK.NUM_2,
  Digit3: RETROK.NUM_3,
  Digit4: RETROK.NUM_4,
  Digit5: RETROK.NUM_5,
  Digit6: RETROK.NUM_6,
  Digit7: RETROK.NUM_7,
  Digit8: RETROK.NUM_8,
  Digit9: RETROK.NUM_9,

  // Numpad
  Numpad0: RETROK.NUM_0,
  Numpad1: RETROK.NUM_1,
  Numpad2: RETROK.NUM_2,
  Numpad3: RETROK.NUM_3,
  Numpad4: RETROK.NUM_4,
  Numpad5: RETROK.NUM_5,
  Numpad6: RETROK.NUM_6,
  Numpad7: RETROK.NUM_7,
  Numpad8: RETROK.NUM_8,
  Numpad9: RETROK.NUM_9,
  NumpadEnter: RETROK.RETURN,
  NumpadAdd: RETROK.PLUS,
  NumpadSubtract: RETROK.MINUS,
  NumpadMultiply: RETROK.ASTERISK,
  NumpadDivide: RETROK.SLASH,
  NumpadDecimal: RETROK.PERIOD,

  // Teclas de Edición y Sistema
  Enter: RETROK.RETURN,
  Space: RETROK.SPACE,
  Escape: RETROK.ESCAPE,
  Backspace: RETROK.BACKSPACE,
  Tab: RETROK.TAB,
  Delete: RETROK.DELETE,
  Insert: RETROK.INSERT,
  Home: RETROK.HOME,
  End: RETROK.END,
  PageUp: RETROK.PAGEUP,
  PageDown: RETROK.PAGEDOWN,

  // Flechas Direccionales
  ArrowUp: RETROK.UP,
  ArrowDown: RETROK.DOWN,
  ArrowLeft: RETROK.LEFT,
  ArrowRight: RETROK.RIGHT,

  // Modificadores
  ShiftLeft: RETROK.LSHIFT,
  ShiftRight: RETROK.RSHIFT,
  ControlLeft: RETROK.LCTRL,
  ControlRight: RETROK.RCTRL,
  AltLeft: RETROK.LALT,
  AltRight: RETROK.RALT,
  CapsLock: RETROK.CAPSLOCK,

  // Puntuación y Símbolos
  Minus: RETROK.MINUS,
  Equal: RETROK.EQUALS,
  BracketLeft: RETROK.LEFTBRACKET,
  BracketRight: RETROK.RIGHTBRACKET,
  Backslash: RETROK.BACKSLASH,
  Semicolon: RETROK.SEMICOLON,
  Quote: RETROK.QUOTE,
  Backquote: RETROK.BACKQUOTE,
  Comma: RETROK.COMMA,
  Period: RETROK.PERIOD,
  Slash: RETROK.SLASH,

  // Teclas de Función F1-F12
  F1: RETROK.F1,
  F2: RETROK.F2,
  F3: RETROK.F3,
  F4: RETROK.F4,
  F5: RETROK.F5,
  F6: RETROK.F6,
  F7: RETROK.F7,
  F8: RETROK.F8,
  F9: RETROK.F9,
  F10: RETROK.F10,
  F11: RETROK.F11,
  F12: RETROK.F12
};

/**
 * Traduce un evento KeyboardEvent del DOM al scancode RETROK correspondientes
 */
export function lookupRetroKey(event: KeyboardEvent): number | undefined {
  return DOM_TO_RETROK_MAP[event.code];
}
