/**
 * @file asset_manifest.cpp
 * @brief Auto-generated asset manifest for WebAssembly builds
 * 
 * This file is automatically generated by tools/generate_asset_manifest.py
 * DO NOT EDIT MANUALLY - your changes will be overwritten!
 */

#include "embedded_vfs.h"
#include "utils/log.hpp"

namespace devilution {

// Forward declarations for embedded asset data
extern const uint8_t asset_arena_church_dun_data[];
extern const size_t asset_arena_church_dun_size;
extern const uint8_t asset_arena_circle_of_death_dun_data[];
extern const size_t asset_arena_circle_of_death_dun_size;
extern const uint8_t asset_arena_hell_dun_data[];
extern const size_t asset_arena_hell_dun_size;
extern const uint8_t asset_data_boxleftend_clx_data[];
extern const size_t asset_data_boxleftend_clx_size;
extern const uint8_t asset_data_boxmiddle_clx_data[];
extern const size_t asset_data_boxmiddle_clx_size;
extern const uint8_t asset_data_boxrightend_clx_data[];
extern const size_t asset_data_boxrightend_clx_size;
extern const uint8_t asset_data_charbg_clx_data[];
extern const size_t asset_data_charbg_clx_size;
extern const uint8_t asset_data_dirtybuc_clx_data[];
extern const size_t asset_data_dirtybuc_clx_size;
extern const uint8_t asset_data_dirtybucp_clx_data[];
extern const size_t asset_data_dirtybucp_clx_size;
extern const uint8_t asset_data_health_clx_data[];
extern const size_t asset_data_health_clx_size;
extern const uint8_t asset_data_healthbox_clx_data[];
extern const size_t asset_data_healthbox_clx_size;
extern const uint8_t asset_data_hintbox_clx_data[];
extern const size_t asset_data_hintbox_clx_size;
extern const uint8_t asset_data_hintboxbackground_clx_data[];
extern const size_t asset_data_hintboxbackground_clx_size;
extern const uint8_t asset_data_hinticons_clx_data[];
extern const size_t asset_data_hinticons_clx_size;
extern const uint8_t asset_data_monstertags_clx_data[];
extern const size_t asset_data_monstertags_clx_size;
extern const uint8_t asset_data_panel8buc_clx_data[];
extern const size_t asset_data_panel8buc_clx_size;
extern const uint8_t asset_data_panel8bucp_clx_data[];
extern const size_t asset_data_panel8bucp_clx_size;
extern const uint8_t asset_data_resistance_clx_data[];
extern const size_t asset_data_resistance_clx_size;
extern const uint8_t asset_data_stash_clx_data[];
extern const size_t asset_data_stash_clx_size;
extern const uint8_t asset_data_stashnavbtns_clx_data[];
extern const size_t asset_data_stashnavbtns_clx_size;
extern const uint8_t asset_data_talkbutton_clx_data[];
extern const size_t asset_data_talkbutton_clx_size;
extern const uint8_t asset_data_xpbar_clx_data[];
extern const size_t asset_data_xpbar_clx_size;
extern const uint8_t asset_fonts_black_trn_data[];
extern const size_t asset_fonts_black_trn_size;
extern const uint8_t asset_fonts_blue_trn_data[];
extern const size_t asset_fonts_blue_trn_size;
extern const uint8_t asset_fonts_buttonface_trn_data[];
extern const size_t asset_fonts_buttonface_trn_size;
extern const uint8_t asset_fonts_buttonpushed_trn_data[];
extern const size_t asset_fonts_buttonpushed_trn_size;
extern const uint8_t asset_fonts_gamedialogred_trn_data[];
extern const size_t asset_fonts_gamedialogred_trn_size;
extern const uint8_t asset_fonts_gamedialogwhite_trn_data[];
extern const size_t asset_fonts_gamedialogwhite_trn_size;
extern const uint8_t asset_fonts_gamedialogyellow_trn_data[];
extern const size_t asset_fonts_gamedialogyellow_trn_size;
extern const uint8_t asset_fonts_goldui_trn_data[];
extern const size_t asset_fonts_goldui_trn_size;
extern const uint8_t asset_fonts_golduis_trn_data[];
extern const size_t asset_fonts_golduis_trn_size;
extern const uint8_t asset_fonts_grayui_trn_data[];
extern const size_t asset_fonts_grayui_trn_size;
extern const uint8_t asset_fonts_grayuis_trn_data[];
extern const size_t asset_fonts_grayuis_trn_size;
extern const uint8_t asset_fonts_orange_trn_data[];
extern const size_t asset_fonts_orange_trn_size;
extern const uint8_t asset_fonts_red_trn_data[];
extern const size_t asset_fonts_red_trn_size;
extern const uint8_t asset_fonts_white_trn_data[];
extern const size_t asset_fonts_white_trn_size;
extern const uint8_t asset_fonts_whitegold_trn_data[];
extern const size_t asset_fonts_whitegold_trn_size;
extern const uint8_t asset_fonts_yellow_trn_data[];
extern const size_t asset_fonts_yellow_trn_size;
extern const uint8_t asset_gendata_cut2w_clx_data[];
extern const size_t asset_gendata_cut2w_clx_size;
extern const uint8_t asset_gendata_cut3w_clx_data[];
extern const size_t asset_gendata_cut3w_clx_size;
extern const uint8_t asset_gendata_cut4w_clx_data[];
extern const size_t asset_gendata_cut4w_clx_size;
extern const uint8_t asset_gendata_cutgatew_clx_data[];
extern const size_t asset_gendata_cutgatew_clx_size;
extern const uint8_t asset_gendata_cutl1dw_clx_data[];
extern const size_t asset_gendata_cutl1dw_clx_size;
extern const uint8_t asset_gendata_cutportrw_clx_data[];
extern const size_t asset_gendata_cutportrw_clx_size;
extern const uint8_t asset_gendata_cutstartw_clx_data[];
extern const size_t asset_gendata_cutstartw_clx_size;
extern const uint8_t asset_gendata_cutttw_clx_data[];
extern const size_t asset_gendata_cutttw_clx_size;
extern const uint8_t asset_gendata_pause_trn_data[];
extern const size_t asset_gendata_pause_trn_size;
extern const uint8_t asset_levels_l1data_sklkngt_dun_data[];
extern const size_t asset_levels_l1data_sklkngt_dun_size;
extern const uint8_t asset_levels_l2data_bonechat_dun_data[];
extern const size_t asset_levels_l2data_bonechat_dun_size;
extern const uint8_t asset_levels_towndata_automap_dun_data[];
extern const size_t asset_levels_towndata_automap_dun_size;
extern const uint8_t asset_ui_art_creditsw_clx_data[];
extern const size_t asset_ui_art_creditsw_clx_size;
extern const uint8_t asset_ui_art_diablo_pal_data[];
extern const size_t asset_ui_art_diablo_pal_size;
extern const uint8_t asset_ui_art_dvl_but_sml_clx_data[];
extern const size_t asset_ui_art_dvl_but_sml_clx_size;
extern const uint8_t asset_ui_art_dvl_lrpopup_clx_data[];
extern const size_t asset_ui_art_dvl_lrpopup_clx_size;
extern const uint8_t asset_ui_art_mainmenuw_clx_data[];
extern const size_t asset_ui_art_mainmenuw_clx_size;
void EmbeddedVFS::RegisterAssetsFromManifest()
{
    LogInfo("🌐 WebAssembly: Asset manifest disabled for initial build");
    // Asset registration disabled for now - using stub implementation
}

} // namespace devilution