"""
make_maps.py - Map generator for NIGHTMARE (3 Dungeon Levels)
Each map is 40x28 tiles (standard Genesis NTSC screen: 320x224 px).
Each cell is a 16-bit word tile index (or byte index).
Also generates spawn coordinates for Player, Monsters, and Stairs.
"""

import os

# Tile indices:
# 0 = Empty/Void
# 1 = Stone Floor Clean
# 2 = Stone Floor Cracked
# 3 = Stone Floor Blood
# 4 = Wall Top
# 5 = Wall Face
# 6 = Wall with Torch
# 7 = Stairs Down
# 8 = Pillar / Altar
# 9 = Runic Floor (Boss Arena)

MAP_W = 40
MAP_H = 28

def build_level1():
    """Level 1: Ashen Catacombs"""
    grid = [[1 for _ in range(MAP_W)] for _ in range(MAP_H)]
    
    # Outer walls
    for x in range(MAP_W):
        grid[0][x] = 4
        grid[1][x] = 5
        grid[MAP_H-1][x] = 4
        grid[MAP_H-2][x] = 5
    for y in range(MAP_H):
        grid[y][0] = 4
        grid[y][1] = 5
        grid[y][MAP_W-1] = 4
        grid[y][MAP_W-2] = 5

    # Torches along walls
    for x in [6, 12, 18, 24, 30]:
        grid[1][x] = 6
        grid[MAP_H-2][x] = 6

    # Interior pillars & walls
    for y in [7, 8, 9, 17, 18, 19]:
        for x in [8, 9, 18, 19, 28, 29]:
            grid[y][x] = 8

    # Some cracked and blood floors
    for x, y in [(5, 5), (14, 12), (22, 7), (32, 15), (10, 21), (25, 22)]:
        grid[y][x] = 2
    for x, y in [(12, 6), (20, 16), (27, 8), (15, 20)]:
        grid[y][x] = 3

    # Stairs down at bottom right
    grid[22][34] = 7

    # Spawns: Player at (5, 5) -> Pixel (5*8, 5*8) = (40, 40)
    # Monsters: 5 skeletons
    monsters = [
        (14 * 8, 8 * 8, 0),   # Skeleton 1 (type 0)
        (24 * 8, 6 * 8, 0),   # Skeleton 2
        (15 * 8, 16 * 8, 0),  # Skeleton 3
        (25 * 8, 20 * 8, 0),  # Skeleton 4
        (32 * 8, 12 * 8, 0),  # Skeleton 5
    ]

    return grid, (40, 40), (34 * 8, 22 * 8), monsters

def build_level2():
    """Level 2: Crypt of the Martyrs"""
    grid = [[1 for _ in range(MAP_W)] for _ in range(MAP_H)]
    
    # Outer walls
    for x in range(MAP_W):
        grid[0][x] = 4
        grid[1][x] = 5
        grid[MAP_H-1][x] = 4
        grid[MAP_H-2][x] = 5
    for y in range(MAP_H):
        grid[y][0] = 4
        grid[y][1] = 5
        grid[y][MAP_W-1] = 4
        grid[y][MAP_W-2] = 5

    # Torches
    for x in [8, 16, 24, 32]:
        grid[1][x] = 6
        grid[MAP_H-2][x] = 6

    # Crypt divider wall with corridor openings
    for y in range(4, 23):
        grid[y][14] = 4
        grid[y][25] = 4
    # Door openings
    grid[10][14] = 1
    grid[11][14] = 1
    grid[16][25] = 1
    grid[17][25] = 1

    # Pillars
    for x, y in [(6, 8), (6, 18), (20, 8), (20, 18), (32, 8), (32, 18)]:
        grid[y][x] = 8

    # Heavy blood in crypt
    for x, y in [(8, 12), (18, 14), (20, 12), (28, 10), (30, 20), (10, 16)]:
        grid[y][x] = 3

    # Stairs down at top right
    grid[5][34] = 7

    # Spawns
    monsters = [
        (8 * 8, 14 * 8, 0),   # Skeleton
        (10 * 8, 20 * 8, 1),  # Ghoul (type 1)
        (18 * 8, 6 * 8, 0),   # Skeleton
        (22 * 8, 16 * 8, 1),  # Ghoul
        (20 * 8, 22 * 8, 0),  # Skeleton
        (30 * 8, 8 * 8, 1),   # Ghoul
        (34 * 8, 16 * 8, 0),  # Skeleton
    ]

    return grid, (40, 100), (34 * 8, 5 * 8), monsters

def build_level3():
    """Level 3: Sanctum of Agony (Boss Arena)"""
    grid = [[1 for _ in range(MAP_W)] for _ in range(MAP_H)]
    
    # Outer walls
    for x in range(MAP_W):
        grid[0][x] = 4
        grid[1][x] = 5
        grid[MAP_H-1][x] = 4
        grid[MAP_H-2][x] = 5
    for y in range(MAP_H):
        grid[y][0] = 4
        grid[y][1] = 5
        grid[y][MAP_W-1] = 4
        grid[y][MAP_W-2] = 5

    # Torches all around arena
    for x in range(4, 36, 4):
        grid[1][x] = 6
        grid[MAP_H-2][x] = 6

    # Great Runic Circle in center (12x10 tiles)
    for y in range(8, 19):
        for x in range(14, 26):
            grid[y][x] = 9

    # Four ceremonial sacrificial pillars
    grid[6][10] = 8
    grid[6][29] = 8
    grid[21][10] = 8
    grid[21][29] = 8

    # The Boss: The Flayer at (20*8, 13*8) = (160, 104)
    boss_spawn = [(20 * 8, 13 * 8, 2)] # Type 2 = Boss

    return grid, (40, 112), (0, 0), boss_spawn

def export_maps(output_path):
    levels = [
        ("Level1", build_level1()),
        ("Level2", build_level2()),
        ("Level3", build_level3()),
    ]

    with open(output_path, 'w', encoding='utf-8') as f:
        f.write("; ================================================================\n")
        f.write("; NIGHTMARE GENESIS — DUNGEON MAP LAYOUTS & SPAWN DATA\n")
        f.write("; Generated by make_maps.py\n")
        f.write("; ================================================================\n\n")

        # Map pointers table
        f.write("Map_Pointers:\n")
        for name, _ in levels:
            f.write(f"    dc.l    {name}_Tiles\n")
            f.write(f"    dc.l    {name}_Spawns\n")
        f.write("\n")

        for name, (grid, player_spawn, stairs_spawn, monsters) in levels:
            f.write(f"; --- {name} Tiles (40x28 = 1120 tiles) ---\n")
            f.write(f"{name}_Tiles:\n")
            for row in grid:
                words = [f"${tile:04X}" for tile in row]
                f.write("    dc.w    " + ", ".join(words) + "\n")
            f.write(f"{name}_Tiles_End:\n\n")

            f.write(f"{name}_Spawns:\n")
            f.write(f"    dc.w    {player_spawn[0]}, {player_spawn[1]}  ; Player X, Y\n")
            f.write(f"    dc.w    {stairs_spawn[0]}, {stairs_spawn[1]}  ; Stairs X, Y\n")
            f.write(f"    dc.w    {len(monsters)}                        ; Monster count\n")
            for mx, my, mtype in monsters:
                f.write(f"    dc.w    {mx}, {my}, {mtype}               ; X, Y, Type\n")
            f.write("\n")

    print(f"Exported maps to {output_path}")

if __name__ == '__main__':
    out_file = os.path.join(os.path.dirname(__file__), '..', 'assets', 'maps.inc')
    export_maps(out_file)
